templateDir: aem

variants:
- variant: aem-author
- variant: aem-publish

files:

# Define a AEM content package containing OSGi configurations from a Sling Provisioning file
- file: sling-provisioning.provisioning
  dir: packages
  template: sling-provisioning.provisioning.hbs
  # Transform OSGi configs from provisoning file to AEM content package
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: config-sample
      packageType: container
      description: The description of the sample package.
      version: "${version}"
      rootPath: /apps/sample/config
      filters:
      - filter: /apps/sample

# Define a AEM content package with some JCR content (Sling Mapping Example)
- file: sling-mapping.json
  dir: packages
  template: sling-mapping.json.hbs
  # Example for disabling a FileVault filter
  validatorOptions:
    contentPackage.validatorsSettings:
      jackrabbit-filter:
        isDisabled: true
  # Transform JSON file to AEM content package
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: mapping-sample
      packageType: content
      rootPath: /etc/map/http
      filters:
      - filter: /etc/map/http
        rules:
        - rule: exclude
          pattern: /etc/map/http
        - rule: include
          pattern: /etc/map/http/.*
        - rule: exclude
          pattern: /etc/map/http/AppMeasurementBridge
  variants:
  - aem-publish

# AEM Systems users with ACLs
- file: aem-systemusers.json
  dir: packages
  template: aem-systemusers.json.hbs
  # Transform JSON file to AEM content package
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: aem-systemusers
      acHandling: merge
      rootPath: /
      filters:
      - filter: /content/rep:policy
      - filter: /home/users/system/sample/sampleSystemUser

# AEM Replication (Author)
- file: aem-replicationagents.json
  dir: packages
  template: aem-replicationagents.json.hbs
  # Example for reconfiguring a FileVault filter
  validatorOptions:
    contentPackage.validatorsSettings:
      jackrabbit-filter:
        options:
          validRoots: /etc/replication
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: aem-cms-author-replicationagents
      packageType: content
      rootPath: /etc/replication
      filters:
      - filter: /etc/replication/agents.author

# Oak Index
- file: aem-cms-oak-index.json
  dir: packages
  template: aem-cms-oak-index.json.hbs
  postProcessors:
    - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: aem-aem-cms-oak-index
      packageType: application
      rootPath: /oak:index
      allowIndexDefinitions: true
  validatorOptions:
    contentPackage.validatorsSettings:
      jackrabbit-packagetype:
        options:
          immutableRootNodeNames: apps,libs,oak:index

# Download AEM content package and extract properties
- url: mvn:io.wcm/io.wcm.caconfig.editor.package//zip
  dir: packages

# Define a AEM content package with a generated HTML file and another copied file
- file: index.html
  dir: packages
  template: index.html.hbs
- file: content-sample.json
  dir: packages
  template: content-sample.json.hbs
  # Transform JSON file to AEM content package
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: content-sample
      packageType: content
      rootPath: /content/sample
      files:
      # Include generated HTML file in content package and delete the file afterwards from filesystem
      - file: index.html
        dir: packages
        path: /content/sample/index.html
        delete: true
      # Include file from classpath in Content package
      - url: classpath:wcm-io-package-thumbnail.png
        path: /content/sample/index.png
      # Custom properties for package metadata
      properties:
        custom.property1: value1
        custom.property2: 123

# ACS AEM Commons
- url: mvn:com.adobe.acs/acs-aem-commons-ui.apps//zip
  dir: packages
  postProcessorOptions:
    contentPackage.packageType: application
- url: mvn:com.adobe.acs/acs-aem-commons-ui.content//zip
  dir: packages
  postProcessorOptions:
    contentPackage.packageType: content


# Defines configuration parameters and default values
config:

  contentPackage:
    group: sample
    version: "${version}"
    thumbnailImage: classpath:/wcm-io-package-thumbnail.png

  jvm:
    path: /path/to/java
    heapspace:
      min: 512m
      max: 2048m
    permgenspace:
      max: 256m

  replication:
    author:
      publishTargets:
      #- name: publish1
      #  url: http://localhost:4503
      #  transportUser: admin
      #  transportPassword: admin

  var1: Value 1
