# Project-specific AEM configuration

# Inherit default AEM functionality from "AEM Definitions", see http://devops.wcm.io/conga/definitions/aem/
inherits:
- role: aem-cms

variants:
- variant: aem-author
- variant: aem-publish

templateDir: wcmio-archetype-cloud-aem-cms

files:


# ACS AEM Commons
- url: mvn:com.adobe.acs/acs-aem-commons-bundle
  dir: bundles
- url: mvn:com.adobe.acs/acs-aem-commons-ui.apps//zip
  dir: packages
  postProcessorOptions:
    contentPackage.packageType: application
- url: mvn:com.adobe.acs/acs-aem-commons-ui.content//zip
  dir: packages
  postProcessorOptions:
    contentPackage.packageType: content

# AEM OSGi System Configuration
- file: wcmio-archetype-cloud-aem-cms-config.provisioning
  dir: packages
  template: wcmio-archetype-cloud-aem-cms-config.provisioning.hbs
  postProcessors:
  - aem-contentpackage-osgiconfig
  postProcessorOptions:
    contentPackage:
      name: wcmio-archetype-cloud-aem-cms-config
      rootPath: /apps/wcmio-archetype-cloud/config
      filters:
      - filter: /apps/wcmio-archetype-cloud
        rules:
        - rule: include
          pattern: /apps/wcmio-archetype-cloud/config(\..*)?(/.*)?
        - rule: exclude
          pattern: /apps/wcmio-archetype-cloud/config/rewriter(/.*)?

# Include URL handler in Sling Rewriter configuration
- file: wcmio-archetype-cloud-aem-cms-rewriter-config.json
  dir: packages
  template: wcmio-archetype-cloud-aem-cms-rewriter-config.json.hbs
  validatorOptions:
    contentPackage.validatorsSettings:
      jackrabbit-filter:
        options:
          validRoots: /apps/wcmio-archetype-cloud/config
  postProcessors:
  - aem-contentpackage
  postProcessorOptions:
    contentPackage:
      name: wcmio-archetype-cloud-aem-cms-rewriter-config
      packageType: application
      rootPath: /apps/wcmio-archetype-cloud/config/rewriter

# wcm.io
- url: mvn:io.wcm/io.wcm.caconfig.extensions
  dir: bundles
- url: mvn:io.wcm/io.wcm.caconfig.editor
  dir: bundles
- url: mvn:io.wcm/io.wcm.sling.commons
  dir: bundles
- url: mvn:io.wcm/io.wcm.sling.models
  dir: bundles
- url: mvn:io.wcm/io.wcm.wcm.commons
  dir: bundles
- url: mvn:io.wcm/io.wcm.wcm.parsys
  dir: bundles
- url: mvn:io.wcm/io.wcm.wcm.ui.granite
  dir: bundles
- url: mvn:io.wcm/io.wcm.wcm.ui.clientlibs
  dir: bundles
- url: mvn:io.wcm/io.wcm.handler.commons
  dir: bundles
- url: mvn:io.wcm/io.wcm.handler.url
  dir: bundles
- url: mvn:io.wcm/io.wcm.handler.media
  dir: bundles
- url: mvn:io.wcm/io.wcm.handler.link
  dir: bundles
- url: mvn:io.wcm/io.wcm.handler.richtext
  dir: bundles
- url: mvn:io.wcm/io.wcm.wcm.core.components
  dir: bundles

# Application bundles andpackages
- url: mvn:io.wcm.devops.conga.plugins.aem.it/io.wcm.devops.conga.plugins.aem.it.aemcloud.core
  dir: bundles

# Application conf content package
- url: mvn:io.wcm.devops.conga.plugins.aem.it/io.wcm.devops.conga.plugins.aem.it.aemcloud.conf-content//zip
  dir: packages
  condition: ${app.confContent}

# Application sample content package
- url: mvn:io.wcm.devops.conga.plugins.aem.it/io.wcm.devops.conga.plugins.aem.it.aemcloud.sample-content//zip
  dir: packages
  condition: ${app.sampleContent}


# Defines configuration parameters and default values
config:
  contentPackage:
    group: it
    version: ${version}

  aem:
    # Disable user tracking in author environment
    disableAuthorUsageStatisticsCollection: false

  app:
    confContent: true
    sampleContent: false

  # Log levels
  log:
    projectSpecificLogLevel: warn
