# Defines an environment

nodes:

# Example nodes
- node: aem-author
  roles:
  - role: aem
    variant: aem-author
- node: aem-publish
  roles:
  - role: aem
    variant: aem-publish
- node: webserver
  roles:
  - role: webserver

# Tenant defintions
tenants:

# Tenant with two tenant roles (can be used for filtering file multiply)
- tenant: tenant1
  roles:
  - website
  - application
  config:
    domain: dev.mysite.de
    httpd:
      serverPort: 8080
      serverPortSsl: 8443
      enforceSsl: true

# Tenant with one tenant roles
- tenant: tenant2
  roles:
  - website
  config:
    domain: dev.mysite.fr

config:
  replication:
    author:
      publishTargets:
      - name: publish1
        url: http://localhost:4503
        transportUser: myuser
        transportPassword: mypassword
