# Defines an environment

nodes:

# Example nodes
- node: aem
  roles:
  - role: aem
- node: webserver
  roles:
  - role: webserver

# Tenant defintions
tenants:

# Tenant with two tenant roles (can be used for filtering file multiply)
- tenant: tenant1
  roles:
  - website
  - application
  config:
    domain: mysite.de
    website.hostname: www.${domain}

# Tenant with one tenant roles
- tenant: tenant2
  roles:
  - website
  config:
    domain: mysite.fr
    website.hostname: www.${domain}


# Export definitions
exportModel:
- node: yaml
