# AEM configuration for local development environment

nodes:

- node: aem-author
  roles:
  - role: wcmio-archetype-aem65-aem-cms
    variant: aem-author
  config:
    replication.author.publishTargets:
    - name: publish
      url: ${maven::sling.publish.url}
      transportUser: admin
      transportPassword: admin

- node: aem-publish
  roles:
  - role: wcmio-archetype-aem65-aem-cms
    variant: aem-publish


config:
  contentPackage.group: it

  app:
    # Default log level for application code
    logLevel: info
    # Whether to deploy conf content with editable template definitions
    confContent: true
    # Whether to deploy sample content
    sampleContent: true

  quickstart:
    # Enable Apache Sling DavEx Servlet to be able to use CRXDE Lite
    enableDavEx: true
